name: Latest publications workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
permissions:
  contents: write
jobs:
  update-readme-with-publications:
    name: Update this repo's README with latest publications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: PUBLICATION
          feed_list: "https://paulobruno.github.io/feed.xml"
